from tack1 import Animal,Dog,Cat,sey_hallo
from tack2 import Library,Book,Author
from tack3 import Fract,Fractions,Fraction
if __name__ == '__main__':
    print('tack1')
    d = Dog()
    c = Cat()
    sey_hallo(d)
    sey_hallo(c)

    print('tack2')
    a = Author('Oleg', 'UA', 2000)
    print(a)
    a1 = Author('Illya', 'RU', 1999)
    l = Library('LIB')
    print(l)
    b = Book('Pirat', 2014, a)
    b1 = Book('Island', 2010, a1)
    b2 = Book('Pirat in island', 2015, a)
    print(b)
    l.new_book(b, a)
    l.new_book(b1, a1)
    l.new_book(b2, a)
    print(l)
    print(l.group_by_author(a))
    print(a)
    print(l)
    print(l.group_by_year(2014))

    print('tack3')
    f = Fractions(6)
    print(f + 2)
    f2 = Fractions(5)
    print(f + f2)
    print(9 + f)
    print('---------')
    print(f * 4)
    print(4 * f)
    print('_______')
    print(f / 2)
    print('---------------')
    fr = Fract(3, 5)
    fr2 = Fract(1,4)
    print(fr.convert())
    print(fr2.convert())
    print(float(fr.convert())+float(fr2.convert()))
    print(float(fr.convert()) - float(fr2.convert()))
    print(float(fr.convert()) * float(fr2.convert()))
    print(float(fr.convert()) / float(fr2.convert()))